# Generated by Django 3.2.5 on 2021-07-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.CharField(max_length=100)),
                ('news_link', models.URLField(max_length=300)),
                ('image_links', models.URLField(max_length=300)),
                ('news_authors', models.CharField(max_length=100)),
                ('published_date', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('headlines',),
            },
        ),
    ]
