# Generated by Django 3.2.5 on 2021-07-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='stories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
