# Generated by Django 3.2.5 on 2021-07-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210719_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('headline',)},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='headlines',
            new_name='headline',
        ),
    ]
