# Generated by Django 3.2.5 on 2021-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_links',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
