# Generated by Django 3.2.5 on 2021-07-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_image_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
